// <auto-generated />
using System;
using Inventario.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Inventario.Api.Migrations
{
    [DbContext(typeof(InventarioDbContext))]
    [Migration("20251212190407_AddCredentials")]
    partial class AddCredentials
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("Inventario.Api.Entities.Credential", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Label")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordProtected")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Credentials");
                });

            modelBuilder.Entity("Inventario.Api.Entities.Installation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AbonadoMm")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AbonadoMm")
                        .IsUnique();

                    b.ToTable("Installations");
                });

            modelBuilder.Entity("Inventario.Api.Entities.InstallationCredential", b =>
                {
                    b.Property<int>("InstallationId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CredentialId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("InstallationId", "CredentialId");

                    b.HasIndex("CredentialId");

                    b.ToTable("InstallationCredentials");
                });

            modelBuilder.Entity("Inventario.Api.Entities.InstallationCredential", b =>
                {
                    b.HasOne("Inventario.Api.Entities.Credential", "Credential")
                        .WithMany("InstallationCredentials")
                        .HasForeignKey("CredentialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Inventario.Api.Entities.Installation", "Installation")
                        .WithMany("InstallationCredentials")
                        .HasForeignKey("InstallationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Credential");

                    b.Navigation("Installation");
                });

            modelBuilder.Entity("Inventario.Api.Entities.Credential", b =>
                {
                    b.Navigation("InstallationCredentials");
                });

            modelBuilder.Entity("Inventario.Api.Entities.Installation", b =>
                {
                    b.Navigation("InstallationCredentials");
                });
#pragma warning restore 612, 618
        }
    }
}
