// <auto-generated />
using System;
using Inventario.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Inventario.Api.Migrations
{
    [DbContext(typeof(InventarioDbContext))]
    [Migration("20260109191212_AddSystemAssets")]
    partial class AddSystemAssets
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("Inventario.Api.Entities.Credential", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Label")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordProtected")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Credentials");
                });

            modelBuilder.Entity("Inventario.Api.Entities.Installation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AbonadoMm")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AbonadoMm")
                        .IsUnique();

                    b.ToTable("Installations");
                });

            modelBuilder.Entity("Inventario.Api.Entities.InstallationCredential", b =>
                {
                    b.Property<int>("InstallationId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CredentialId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("InstallationId", "CredentialId");

                    b.HasIndex("CredentialId");

                    b.ToTable("InstallationCredentials");
                });

            modelBuilder.Entity("Inventario.Api.Entities.SystemAsset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Firmware")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("InstallationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastSeenAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Manufacturer")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("OpenPortsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("PreferredCredentialId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Protocol")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<int?>("SdkPort")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SerialNumber")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int?>("WebPort")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PreferredCredentialId");

                    b.HasIndex("InstallationId", "IpAddress")
                        .IsUnique();

                    b.ToTable("SystemAssets");
                });

            modelBuilder.Entity("Inventario.Api.Entities.InstallationCredential", b =>
                {
                    b.HasOne("Inventario.Api.Entities.Credential", "Credential")
                        .WithMany("InstallationCredentials")
                        .HasForeignKey("CredentialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Inventario.Api.Entities.Installation", "Installation")
                        .WithMany("InstallationCredentials")
                        .HasForeignKey("InstallationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Credential");

                    b.Navigation("Installation");
                });

            modelBuilder.Entity("Inventario.Api.Entities.SystemAsset", b =>
                {
                    b.HasOne("Inventario.Api.Entities.Installation", "Installation")
                        .WithMany()
                        .HasForeignKey("InstallationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Inventario.Api.Entities.Credential", "PreferredCredential")
                        .WithMany()
                        .HasForeignKey("PreferredCredentialId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Installation");

                    b.Navigation("PreferredCredential");
                });

            modelBuilder.Entity("Inventario.Api.Entities.Credential", b =>
                {
                    b.Navigation("InstallationCredentials");
                });

            modelBuilder.Entity("Inventario.Api.Entities.Installation", b =>
                {
                    b.Navigation("InstallationCredentials");
                });
#pragma warning restore 612, 618
        }
    }
}
